language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
deploy:
  provider: heroku
  on: master
  api_key:
    secure: I6toYb6eJoy6BD6nS2injePe8JcRcIn6yuomC0/nHVbirZ8bs+pH2gEfM8J/0VVycWgdYYTNaqVlD2wbV3cFqd9Bd6uw5u81Eg25t9KPJ3nHZng+4t682tnMVfwBY52oEwz74c/k3NpGQG3mNMmiAOwPdMls5ZGYJRSnsX+ZUCUAdpqvoGuXSmjM/lTnZzJFTO1gfp2rno309+6DtSz83VE8BkjBSJGdiuo8rloWY4N+FRQ3RzTb+AItuXjVx85DAI8SbnjLR200K0IBpwRf4hMuIdAcNvbHJN99vjamt9/HMVbHVbImRj5hXS/z2djE42Akn/T9CWQbQgToi4PbwNCSREQSJ7s766nVaJEaP5B8EodP0a1tF3gmdNJk3dvr00DMOdjO7ZVpVrVLCWfPjVohrCXu6r7Ui7T+TaGhuEf5moYmjYVE5wdpQzL2Aubt5MGcbsLdqC8Wad5sSk6u+FOMdQ8m1bSBKK6O6R4l1ZWCMBkYZ+A6c75cOCTUhSjJQE4Qegk0Iu41eUiTP21gWcCajahG/kHbSNiFXecQNiGd569RbjVfK7hwf2c3UWaCXy6xWjO5mkj/O4haGyaEDzTlJp8PlwjgdTzY2KVtVfXYyEj7b2ABUzGRT/UAx95LQ4wsXrrp42eZiDhLAQ3UWYbJfQPJ35lplK2Yt80g1n0=
